packages:
  - packages/*

catalog:
  "@types/node": ^25
  typescript: ^6
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: ^0.1.24
  vitest: npm:@voidzero-dev/vite-plus-test@latest

catalogMode: prefer
overrides:
  "@voidzero-dev/vite-plus-test>vite": "^8.0.16"
  postcss: "^8.5.10"
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
