# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import types


def call_tool(name: str, args: str) -> str:
    raise NotImplementedError
def list_tools() -> List[types.ToolDefinition]:
    raise NotImplementedError
def log(level: int, message: str) -> None:
    raise NotImplementedError
def stream_emit(event_type: str, data: str) -> None:
    raise NotImplementedError
