# This file is automatically generated by componentize-py
# It is not intended for manual editing.
from typing import TypeVar, Generic, Union, Optional, Protocol, Tuple, List, Any, Self, Callable
from types import TracebackType
from enum import Flag, Enum, auto
from dataclasses import dataclass
from abc import abstractmethod
import weakref

from componentize_py_types import Result, Ok, Err, Some
from ..imports import types

class Agent(Protocol):

    @abstractmethod
    def get_metadata(self) -> str:
        """
        Returns JSON blob matching CreateAgentConfig shape (minus handler).
        Parsed by host with CreateAgentConfigValidationSchema (Zod).
        """
        raise NotImplementedError

    @abstractmethod
    def execute(self, prompt: str, context: str) -> types.AgentResult:
        """
        prompt: string or JSON-serialized structured input.
        context: JSON blob with env, config, session, output_schema.
        """
        raise NotImplementedError


